services:
  app:
    container_name: bet-service-app
    image: bet-service:latest
    networks:
      - bet-service-net
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: main/target/main.jar
    environment:
      APP_SERVER_PORT: "8080"
      KAFKA_HOST: "kafka:9092"
      ROCKETMQ_HOST: "rmqnamesrv:9876"
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - rocketmq-broker

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - bet-service-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      - bet-service-net
    hostname: kafka
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - 8091:8081
    networks:
      - bet-service-net
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092

  namesrv:
    image: apache/rocketmq:5.3.2
    hostname: rmqnamesrv
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    networks:
      - bet-service-net
    command: sh mqnamesrv

  rocketmq-broker:
    image: apache/rocketmq:5.3.2
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    networks:
      - bet-service-net
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on:
      - namesrv
    command: sh mqbroker

  proxy:
    image: apache/rocketmq:5.3.2
    container_name: rmqproxy
    ports:
      - 8180:8080
      - 8181:8081
    networks:
      - bet-service-net
    depends_on:
      - rocketmq-broker
      - namesrv
    restart: on-failure
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    command: sh mqproxy

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 9081:8080
    networks:
      - bet-service-net
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  rocketmq-ui:
    image: apacherocketmq/rocketmq-dashboard
    container_name: rocketmq-ui
    ports:
      - 9082:8080
    networks:
      - bet-service-net
    depends_on:
      - namesrv
    environment:
      NAMESRV_ADDR: rmqnamesrv:9876
      JAVA_OPTS: "-Xms512m -Xmx1024m"

networks:
  bet-service-net:
    driver: bridge
